### ISSUE TITLE
[Zuzana] PDF file verification

### ISSUE THREAD

**Issue by ValentinKuznetsov** [sookyp/PA193_parser#10]
Hi,

Please implement the PDF file basic verification.
You may implement some PDFVerifier class which has all logic related to the verification of the pdf.

Input: the path to a pdf.
Output: Document class or null.

We won't bother with particular error messages for now; it will be enough to know if PDF is malformed or not.

Some ideas how to check the pdf document integrity:
- Not an empty file.
- Not passworded(encrypted)
- Not too big. In order to save some time, we won't bother about optimizations much; just cut out the big files, say, >400 MB.
- Contains /Root object.
- It has %%EOF in the end of the file.
- Version is not higher than XX (for now, let it be 1.4) 
- You are able to parse metadata. (Just call parseMetadata and catch the exception)
- You are able to parse the pages. (Just parse pages and catch the exception)
- .. to be continued.Please update this list as you go.

As far as I know, the pdf gets very complicated starting from version 1.4, so we will restrict our parser for pdfs 1.3 and 1.4.

**Comment by ValentinKuznetsov** [comment]
For new ideas, you can also read this huge document

http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf
Particularly, the paragraph 'file structure' 

our parser will be fail-deadly; if he does not like anything -> get out!

**Comment by ValentinKuznetsov** [comment]
Deadline - no later than Sunday evening we must have at least all points described in the post above, and preferably, something more. :)

**Comment by ValentinKuznetsov** [comment]
see page 727

**Comment by ValentinKuznetsov** [comment]
see also page 699 "H.2 Minimal PDF File"

**Comment by ValentinKuznetsov** [comment]
see 677 "Linearized PDF Document Structure"

**Comment by zmat01** [comment]
**Verification of PDF file**
    Not an empty file.     **done** 
    Not passworded(encrypted)  **not done**
    Not too big. In order to save some time, we won't bother about optimizations much; just cut out the big files, say, >400 MB.        **done** 
    Contains /Root object.    **done**
    It has %%EOF in the end of the file.      **done** 
    Version is not higher than XX (for now, let it be 1.4)       **done**
    You are able to parse metadata. (Just call parseMetadata and catch the exception)     **will be done before commit**
    You are able to parse the pages. (Just parse pages and catch the exception)      **will be done before commit**
Has minimal pdf structure (follows pdf structure)    **not done**
Do we have rights for reading file       **done**

**So it remains to do**
check if file is passworded    (info about this could be somewhere in dictionary)
check if file follows pdf structure
