### ISSUE TITLE
Analyze pdf structure

### ISSUE THREAD

**Issue by ValentinKuznetsov** [sookyp/PA193_parser#4]
The main goal is to analyze the pdf and get an idea where all the forms are stored.

Let's use this thread for discussing all this

**Comment by ValentinKuznetsov** [comment]
Please also post all useful links to this thread

**Comment by ValentinKuznetsov** [comment]
http://resources.infosecinstitute.com/pdf-file-format-basic-structure/

**Comment by ValentinKuznetsov** [comment]
Important note:

if you implement anything and reuse anything from somewhere, post links here!
We include all of them in our final report.

**Comment by ValentinKuznetsov** [comment]
![110612_1237_pdffileform7](https://cloud.githubusercontent.com/assets/3718148/19019336/06ec7006-8885-11e6-84dc-9d671484e026.png)

**Comment by ValentinKuznetsov** [comment]
So, basically, we need to do this:

Parse pages out of document catalog -> Page tree, and after this we parse all stuff from each page 
- Metadata (somewhere in the pdf)

**Comment by zmat01** [comment]
We are able to find couple of things easily
We can find number of pages
/Type/Pages/**Count 1**/Kids[ 3 0 R] 

Language used
/Type/Catalog/Pages 2 0 R/Lang(**cs-CZ**) /StructTreeRoot 8 0 R/MarkInfo<</Marked true

Which filter (coding) was used
/Filter/**FlateDecode**/Length 125

Which font was used  and also encoding type
/Type/Font/Subtype/TrueType/Name/F1/**BaseFont/ABCDEE+Calibri/Encoding**/**WinAnsiEncoding**/FontDescriptor 6 0 R/FirstChar 32/LastChar 97/Widths 14 0 R

The name of author
/Author(**AuthorName**)/Creator

Creation date and modification date
**CreationDate(D:20161002133535)** **/ModDate(D:20161002133535)**

This we are able to find easily..

But we'll need also some decoder for the rest of pdf..  some parts of pdf are encoded..

**Comment by zmat01** [comment]
Here are some other links
http://www.adobe.com/content/dam/Adobe/en/technology/pdfs/PDF_Day_A_Look_Inside.pdf
https://web.archive.org/web/20141010035745/http://gnupdf.org/Introduction_to_PDF
https://blog.didierstevens.com/2008/05/19/pdf-stream-objects/

The most detailed is documentation of Adobe .. but it has almost 800 pages..
http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf

**Comment by ValentinKuznetsov** [comment]
https://kenai.com/projects/pdf-library/sources/subversion/content/PDFPageTree.java?rev=11

**Comment by ValentinKuznetsov** [comment]
https://kenai.com/projects/pdf-library/sources/subversion/show
